command /npcc <text> <text>:
	usage: /warnpc <NPCレベル> <NPCの名前>
	trigger:
		create citizen named " &7[Lv%arg-1%] &f%arg-2%" at location of player as a player
		
command /np <text> <text>:
	trigger:
		if arg-1 is "del":
			execute player command "/npc select"
			execute player command "/npc remove"
		if arg-1 is "skin":
			execute player command "/npc select"
			execute player command "/npc skin %arg-2% -p"

on npc right click:
	if citizen is 52:
		send "test"