command /clan create <text>:
	trigger:
		if length of arg-1 is more than 12:
			send "no"
		else:
			send "yes"
			set {clannameof%player%} to "%arg-1%"
			set {%player%isinclan} to 1
			add player to {clannemberlist%arg-1%::*}
			set {amountofclanmember%arg-1%} to 1
			
on portal:
	if {%player%isinclan} is 1:
		loop all players:
			if {clannameof%loop-player%} is equal to {clannameof%player%}:
				send "yey" to loop-player
			
command /clantest <player>:
	trigger:
		send "clantest"