on right click:
	name of held item contains "Grim Reaper"
	if name of held item contains "Blueprint":
		stop
	if slot 0 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 1 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 2 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 3 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 4 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 5 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 6 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 7 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 8 of player's inventory is diamond axe:
		add 1 to {_t}
	
	if {_t} is more than 2:
		send "&7You can't use this ability when you have more than 2 secondary weapons in hotbar !!"
		stop
	gamemode of player is not spectator
	if distance between player and targeted entity is smaller than 30:
		if level progress of player is smaller than 0.35:
			send "&7You need more mana to use Grim portal !!"
		else:
			if player's target is a player:
				subtract 0.3499 from level progress of the player
				send "&7You activated Grim portal !!"
				teleport player to targeted entity
				# loop living entities in radius 3 of player:
					# if loop-entity is player:
						# exit 1 section
					# if {war.inteam.creeper.%player%} is 1:
						# if {war.inteam.moosh.%loop-entity%} is 1:
							# make player damage loop-entity by 10
					# else if {war.inteam.moosh.%player%} is 1:
						# if {war.inteam.creeper.%loop-entity%} is 1:
							# make player damage loop-entity by 10
					# else:
						# if player is not in world "spawn" or "kihu":
							# make player damage loop-entity by 10
				execute console command "mogsound %player% entity.endermen.teleport 1 0.7"
				
			# else if player's target is arrow:
				# subtract 0.4999 from level progress of the player
				# send "&7You activated Ninja Teleport !!"
				# teleport player to targeted entity
				# execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
				# wait 3 tick
				# execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
				# wait 3 tick
				# execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
				# wait 3 tick
				# execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
	else:
		send "&7You have to target something to use Grim portal !!"
on right click:
	name of held item contains "Warblade of Thanatos"
	if difference between {kunaidash%player%} and now is less than 0.5 seconds:
		stop
	if slot 0 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 1 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 2 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 3 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 4 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 5 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 6 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 7 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 8 of player's inventory is diamond axe:
		add 1 to {_t}
	
	if {_t} is more than 2:
		send "&7You can't use this ability when you have more than 2 secondary weapons in hotbar !!"
		stop
	gamemode of player is not spectator
	# if distance between player and targeted entity is smaller than 30:
	if level progress of player is smaller than 0.4:
		send "&7You need 40%% or more mana to use Grim Glide !!"
	else:
		# if player's target is a player:
		subtract 0.3999 from level progress of the player
		send "&7You activated Grim Glide !!"
		apply unluck to player for 10 second
		push player forward at speed 2
		set {kunaidash%player%} to now
		# teleport player to targeted entity
		# loop living entities in radius 3 of player:
			# if loop-entity is player:
				# exit 1 section
			# if {war.inteam.creeper.%player%} is 1:
				# if {war.inteam.moosh.%loop-entity%} is 1:
					# make player damage loop-entity by 10
			# else if {war.inteam.moosh.%player%} is 1:
				# if {war.inteam.creeper.%loop-entity%} is 1:
					# make player damage loop-entity by 10
			# else:
				# if player is not in world "spawn" or "kihu":
					# make player damage loop-entity by 10
		execute console command "/mogsound %player% magicpro1 1 1.4"
on right click:
	name of held item contains "Ninja Kunai"
	if difference between {kunaidash%player%} and now is less than 0.5 seconds:
		stop
	if slot 0 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 1 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 2 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 3 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 4 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 5 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 6 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 7 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 8 of player's inventory is diamond axe:
		add 1 to {_t}
	
	if {_t} is more than 2:
		send "&7You can't use this ability when you have more than 2 secondary weapons in hotbar !!"
		stop
	gamemode of player is not spectator
	# if distance between player and targeted entity is smaller than 30:
	if level progress of player is smaller than 0.4:
		send "&7You need 40%% or more mana to use Ninja Reflex !!"
	else:
		# if player's target is a player:
		subtract 0.3999 from level progress of the player
		send "&7You activated Ninja Reflex !!"
		apply unluck to player for 10 second
		push player forward at speed 2
		set {kunaidash%player%} to now
		# teleport player to targeted entity
		# loop living entities in radius 3 of player:
			# if loop-entity is player:
				# exit 1 section
			# if {war.inteam.creeper.%player%} is 1:
				# if {war.inteam.moosh.%loop-entity%} is 1:
					# make player damage loop-entity by 10
			# else if {war.inteam.moosh.%player%} is 1:
				# if {war.inteam.creeper.%loop-entity%} is 1:
					# make player damage loop-entity by 10
			# else:
				# if player is not in world "spawn" or "kihu":
					# make player damage loop-entity by 10
		execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
		wait 3 tick
		execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
		wait 3 tick
		execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
		wait 3 tick
		execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
			# wait 3 tick
			# execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
			# wait 3 tick
			# execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
			# wait 3 tick
			# execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
		# else if player's target is arrow:
			# subtract 0.4999 from level progress of the player
			# send "&7You activated Ninja Teleport !!"
			# teleport player to targeted entity
			# execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
			# wait 3 tick
			# execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
			# wait 3 tick
			# execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
			# wait 3 tick
			# execute console command "mogsound %player% entity.bat.takeoff 1 1.5"
	# else:
		# send "&7You have to target something to use Ninja Reflex !!"

on crackshot reload finish:
	lore of held item contains "Monarch Mod":
		execute console command "/execute %player% ~ ~ ~ /particle happyVillager ~ ~ ~ 1 3 1 0.01 50"
		
		heal player
		
		execute console command "mogsound %player% minecraft:entity.experience_orb.pickup 1.3 1.2" 
		wait 2 tick
		execute console command "mogsound %player% minecraft:entity.experience_orb.pickup 1.3 1.3"
		wait 2 tick
		execute console command "mogsound %player% minecraft:entity.experience_orb.pickup 1.3 1.6"

on Damage:
	if attacker is victim:
		stop
	lore of tool of attacker contains "Warlord Mod":
		chance of 40%:
			execute console command "/execute %attacker% ~ ~ ~ /particle fallingdust ~ ~ ~ 1 2 1 0.1 15"
			apply wither 1 to victim for 4 seconds
	lore of tool of attacker contains "Emperor Mod":
		chance of 35%:
			execute console command "/execute %attacker% ~ ~ ~ /particle happyVillager ~ ~ ~ 1 1 1 0.01 15"
		
			heal attacker by 3 heart
			
			execute console command "mogsound %attacker% minecraft:entity.experience_orb.pickup 1.3 1.4" 
			wait 2 tick
			execute console command "mogsound %attacker% minecraft:entity.experience_orb.pickup 1.3 1.6"
			
on right click:
	name of held item contains "Lusha's Harp"
	if slot 0 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 1 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 2 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 3 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 4 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 5 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 6 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 7 of player's inventory is diamond axe:
		add 1 to {_t}
	if slot 8 of player's inventory is diamond axe:
		add 1 to {_t}
	
	if {_t} is more than 2:
		send "&7You can't use this ability when you have more than 2 secondary weapons in hotbar !!"
		stop
		
	if difference between {harpcooldown%player%} and now is less than 2 second:
		stop
		
	execute console command "mogsound %player% aaharp 1 1.5"
	
	loop all players in radius 7 around player:
		if {war.inteam.creeper.%player%} is 1:
			if {war.inteam.creeper.%loop-player%} is 1:
				remove absorption from loop-player
				apply absorption 3 to the loop-player for 10 seconds
		else if {war.inteam.moosh.%player%} is 1:
			if {war.inteam.moosh.%loop-player%} is 1:
				remove absorption from loop-player
				apply absorption 3 to the loop-player for 10 seconds
	
		else:
			remove absorption from loop-player
			apply absorption 3 to the loop-player for 10 seconds
		
		execute console command "/execute %loop-player% ~ ~ ~ /particle note ~ ~ ~ 0 1.5 0 0.05 10"
	set {harpcooldown%player%} to now
# on left click:
	
	# name of held item contains "carb7_at" or "Shepherd_at" or "fiend_st" or "Gritt_at" or "maelstrom_at" or "Bayou_at"
	# if line 1 of lore of held item of player exists:
		# set {_line1} to line 1 of lore of held item of player
	# if line 2 of lore of held item of player exists:
		# set {_line2} to line 2 of lore of held item of player
	# if line 3 of lore of held item of player exists:
		# set {_line3} to line 3 of lore of held item of player
	# if {_line1} is not set:
		# set {_line1} to " "
	# if {_line2} is not set:
		# set {_line2} to " "
	# if {_line3} is not set:
		# set {_line3} to " "
	# if name of held item contains "carb7_at":
		# give crackshot weapon "carb7" with lore "%{_line1}%||%{_line2}%||%{_line3}%" to player
	# if name of held item contains "Shepherd":
		# give crackshot weapon "Shepherd_at" with lore "%{_line1}%||%{_line2}%||%{_line3}%" to player
	# if name of held item contains "fiend_st":
		# give crackshot weapon "fiendsbreath" with lore "%{_line1}%||%{_line2}%||%{_line3}%" to player
	# if name of held item contains "Gritt_at":
		# give crackshot weapon "Gritt" with lore "%{_line1}%||%{_line2}%||%{_line3}%" to player
	# if name of held item contains "maelstrom_at":
		# give crackshot weapon "maelstrom" with lore "%{_line1}%||%{_line2}%||%{_line3}%" to player
	# if name of held item contains "Bayou_at":
		# give crackshot weapon "Bayou" with lore "%{_line1}%||%{_line2}%||%{_line3}%" to player
	# remove held item from player
	# send "&7Opps, something went wrong with your weapon so we exchanged bugged item automatically. Sorry!"
	
#"Called when a weapon is shot. The player is the shooter, event-entity is the projectile and event-string is the weapons name."
# on crackshot shoot:
	# push event-entity upwards at speed 3
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	