on pick up of cooked porkchop:
	add 7 to food bar of player
	heal player by 20 hearts
	wait 1 tick
	remove all cooked porkchop from player's inventory
	message "<gold>You have eaten a porkchop! You are well fed and fully healed!" to player
	play raw sound "random.eat" at player with pitch 1 volume 1.2
	wait 4 tick
	play raw sound "random.eat" at player with pitch 1 volume 1.2
	wait 4 tick
	play raw sound "random.eat" at player with pitch 1 volume 1.2
	wait 4 tick