command /testblock:
	trigger:
		player is op
		add location of player to {testloc::*}
		send "added"
command /testblocks:
	trigger:
		player is op
		loop {testloc::*}:
			set block above loop-value to 160:5


command /pexreload:
	trigger:
		player is op
		execute console command "pex reload"
		send "pex reloaded"

command /windcheck <text>:
	trigger:
		loop all players:
			loop all items in the inventory of loop-player:
				if name of loop-item contains "%arg-1%":
					
					add 1 to {_t%loop-player%}
					if {_t%loop-player%} is not more than 1:
						add 1 to {_t2}
						add name of loop-player to {_t::*}
						
		set {_n} to number of all players
		set {_n2} to {_t2}/{_n}*100
		send "インベントリに%arg-1%入ってる人の名前＝&a%{_t::*}% &b(%{_t2}%人、%{_n2}%%%の所持率)"
		
# command /test:
	# trigger:
		# json("%player%", "&7&oHello, this is a &bsample json&7.||ttp:&bThis is line 1%nl%Wow! line 2%nl%Yet another line|| There's no tag, so I've started a new cluster.||cmd:/ping||ttp:&6&o&lCLICK&f for /ping")
		
		
command /namemc <player>:
	trigger:
		if arg 1 is not set:
			send "https://namemc.com/profile/%name of player%"
			stop
		else:
			send "https://namemc.com/profile/%name of arg-1%"
			
command /givesoundchk <text>:
	trigger:
		player is op
		give a paper named "%arg-1%" with lore "sound check item op only" to player
		
on right click:
	player is op
	if line 1 of lore of held item of player is "sound check item op only":
		execute player command "mogsound %player% %name of held item of player parsed as text% 1 1"

command /hayauti <text>:
	trigger:
		player is op
		set {hayautitext} to arg-1
		set {_t} to 5
		broadcast "&a次の文字を一番はやく正確にタイプした人が勝利です！"
		wait 3 second
		broadcast "&a5秒前..."
		wait a second
		broadcast "&a4秒前..."
		wait a second
		broadcast "&a3秒前..."
		wait a second
		broadcast "&a2秒前..."
		wait a second
		broadcast "&a1秒前..."
		wait a second
		broadcast "&a%{hayautitext}%"
		broadcast "&a上に書かれた通りタイプしてね!この行は書かなくていいよ！"
on chat:
	message is {hayautitext}
	clear {hayautitext}
	broadcast "&a%player%さんが早打ちに勝利しました！やったねたえちゃん！"
				
#(year|month|month name|day of year|day of month|day of week|day name|hours|minutes|seconds) from date %date%
#date %date%'s (year|month|month name|day of year|day of month|day of week|day name|hours|minutes|seconds)
command /padi:
	trigger:
		player is op
		set {_tmpO} to now
		# give a coal named "&6Lucky Bag (%year from date {_tmpO}% %month name from date {_tmpO}%)" to player
		send "Date: %{_tmpO}%"
		send "Year: %year from date {_tmpO}%"
		send "Month: %month from date {_tmpO}%"
		send "Month Name: %month name from date {_tmpO}%"
		send "Day of Year: %day of year from date {_tmpO}%"
		send "Day of Month: %day of month from date {_tmpO}%"
		send "Day of Week: %day of week from date {_tmpO}%"
		send "Day Name: %day name from date {_tmpO}%"
		send "Hour: %hours from date {_tmpO}%"
		send "Minute: %minutes from date {_tmpO}%"
		send "Second: %seconds from date {_tmpO}%"
		
# command /dam:
	# trigger:
		# player is op
		# show 10 villager_angry particles at player offset by 0, 2, 0
# command /dura:
	# trigger:
		# player is op
		# set the damage of held item of player to 20
		
# weapon scope in:
	# player is op
	# send "scope"

# weapon unscope:
	# player is op
	# send "unscope"

command /glow <player>:
	trigger:
		player is op
		remove glowing from player-arg
		apply glowing to player-arg for 10 seconds
		# on crackshot reload:
	# player is op
	# send "%event-string%"
# crackshot reload complete:
	# player is op
	# cancel event
command /wkick <player> <text>:
	trigger:
		player is op
		kick arg-1 because "%arg-2%"
		broadcast "&7%player%が%arg-1%をキックしました！"
		broadcast "&7キック理由: %arg-2%"

# command /testda:
	# trigger:
		# launch creeper firework colored red at player timed 1
		
		# (1¦|2¦flickering |3¦trailing |4¦flickering trailing |5¦trailing flickering (ball, ball large, burst, creeper, star) [firework] [effect] colo[u]red %colors%
		# (1¦|2¦flickering |3¦trailing |4¦flickering trailing |5¦trailing flickering )%firework type% [firework] [effect] colo[u]red %colors% fad(e|ing) [to] %colors%
		
# command /testset:
	# trigger:
		# set {hanabi_location_lobby} to location of player

# command /now:
	# trigger:
		# send "&7The server clock is: %now%"# on right click:
	# player is op
	# push player forward at speed 10

# On CrackShot Reload:
	# player is op:
		# set event-number to 0

# command /pop:
	# trigger:
		# player is op
		# open horse inventory to player

# command /po:
	# trigger:
		# player is op
		# set {test} to held item of player
		# open chest with 1 rows named "&fHerb Cutting Menu" to player
		# wait 1 tick
		# format slot 0 of player with {test} to be unstealable

# command /sword:
	# trigger:
		# player is op
		# give player diamond sword with no nbt
		
# on inventory close:
	# name of inventory is "Anchent Enchant"
	# send "test"
			
# command /popo <text>:
	# trigger:
		# player is op
		# broadcast "しゃーないな%arg-1%さん君に限定武器をあげよう"
		# loop 10 times:
			# execute player command "moggive %arg-1% Vesta 1"

		# on gun shoot:"
	# name of held item contains "leaf"
	# send "test"

# on right click:
	# push player forward at speed 1	
# on inventory click:
	# if name of Clicked Cursor Item contains "shep":
		# send "test"
# command /hat:
	# trigger:
		# player is op
		# if helm of player is set:
			# send "test1"
			# stop
		# set the helm of player to held item of player
	
# command /beacontest:
	# trigger:
		# player is op
		# delete {blocks2::*}
		# delete {blocks1::*}
		# send "A= %{blocks1::*}%"
		# send "B= %{blocks2::*}%"


on damage:
	if damage was caused by fire, burning or melting:
		if victim is in "spawn":
			cancel event

on join:
	set {event%player%} to 0


		

# every 1 tick:
	# loop all players:
		# set bossbar named "test" for loop-player to {bosstime}

# every 1 second:
	# if name of player contains "THE_WAR_Admin":
		# if {domitimerC} is not set:
			# set {domitimerC} to 5
		# if {domitimerC} is 5:
			# broadcast "5"
		# if {domitimerC} is 4:
			# broadcast "4"
		# if {domitimerC} is 3:
			# broadcast "3"
		# if {domitimerC} is 2:
			# broadcast "2"
		# if {domitimerC} is 1:
			# broadcast "1"
		# if {domitimerC} is 0:
			# broadcast "senryo-"


# command /helm:
	# trigger:
		# player is op
		# set helmet of player to air

# command /kubaru <number>:
	# trigger:
		# player is op
		# if {pricecooldown%player%} and now is less than 1 minutes:
			# send "&7Please don't spam this command :)" to player
			# stop
			
		# else if player is holding a diamond axe:
		
			# broadcast "<light grey>[Lv%level of player%]<white> %player%: %name of held item of player%<white>を&a%arg-1%&fで売ります！"
			# <light green>$%arg-1%<white>で売ってます！"
			# broadcast "<light grey>[Lv%level of player%]<white> %player%: %1st line of lore of held item of player% %2nd line of lore of held item of player%"
			
			# set {pricecooldown%player%} to now
			
		# else:
			# send "&7You must use this command while holding a gun !!" to player


# on right click:
	# name of player is "N00bFan":
	# loop all players:
		# name of loop-player contains "ryukiti":
			# send "clicked" to loop-player



# on right click:
	# player is op
	# play (resource|[custom ]sound) [sound] pack %string% to %player% [at %location%]
	# play sound pack "shoot.ak" to player at location of player

# every 10 tick:
	# loop all players:
		# if {oto%loop-player%} is 1:
			# execute console command "mogsound %loop-player% ui.button.click 1.2 0.5"
			
# command /kd+ <offline player>:
	# trigger:
		# player is op
		# add 5000 to {killkd%arg-1%}
		
# command /kd- <offline player>:
	# trigger:
		# player is op
		# subtract 5000 from {killkd%arg-1%}
			
# command /kd <offline player>:
	# trigger:
		# player is op
		# send "&7%{killkd%arg-1%}% kills, %{deadkd%arg-1%}% deaths." to player
		# send "&7%{killkd%arg-1%}/{deadkd%arg-1%}% kd" to player
		
# command /kda <offline player>:
	# trigger:
		# player is op
		# broadcast "&7でばっぐ: %arg-1%さんのキルレだよー"
		# broadcast "&7でばっぐ: %{killkd%arg-1%}% kills, %{deadkd%arg-1%}% deaths."
		# broadcast "&7でばっぐ: %{killkd%arg-1%}/{deadkd%arg-1%}%キルレ"

# command /kdclear <offline player>:
	# trigger:
		# player is op
		# broadcast "&7でばっぐ: %arg-1%さんキルレのDBけしたぞー"
		# set {killkd%arg-1%} to 0
		# set {deadkd%arg-1%} to 0
# on damage:
	# add attacker to {%victim%assisttag::}


# on right click:
	# player is op
	# shoot ender pearl from player at speed 1
# on damage:
	# damage cause is fall
	# cancel event
# command /yey:
	# trigger:


on right click holding note block:
	name of held item contains "Music Box I"
	if difference between {musicbox1%player%} and now is less than 46 tick:
		stop
	else:
		set {musicbox1%player%} to now
		execute console command "mogsound %player% block.note.pling 1.2 1.587"#d
		wait 6 tick
		execute console command "mogsound %player% block.note.pling 1.2 1.189"
		wait 3 tick
		execute console command "mogsound %player% block.note.pling 1.2 1.189"
		wait 3 tick
		execute console command "mogsound %player% block.note.pling 1.2 1.260"
		wait 6 tick
		execute console command "mogsound %player% block.note.pling 1.2 1.189"#a
		wait 12 tick
		execute console command "mogsound %player% block.note.pling 1.2 1.498"
		wait 6 tick
		execute console command "mogsound %player% block.note.pling 1.2 1.587"#d
		
	
# on right click:
	# player is op:
		# execute console command "mogsound %player% block.note.pling 1.2 0.500"#f+
		# execute console command "mogsound %player% block.note.pling 1.2 0.530"#g
		# execute console command "mogsound %player% block.note.pling 1.2 0.561"#g+ a-
		# execute console command "mogsound %player% block.note.pling 1.2 0.595"#a
		# execute console command "mogsound %player% block.note.pling 1.2 0.630"#a+ b-
		# execute console command "mogsound %player% block.note.pling 1.2 0.667"#b
		# execute console command "mogsound %player% block.note.pling 1.2 0.707"#c
		# execute console command "mogsound %player% block.note.pling 1.2 0.749"#c+ d-
		# execute console command "mogsound %player% block.note.pling 1.2 0.794"#d
		# execute console command "mogsound %player% block.note.pling 1.2 0.841"#d+ e-
		# execute console command "mogsound %player% block.note.pling 1.2 0.891"#e
		# execute console command "mogsound %player% block.note.pling 1.2 0.944"#f
		# execute console command "mogsound %player% block.note.pling 1.2 1.000"#f+ g-
		# execute console command "mogsound %player% block.note.pling 1.2 1.059"#g
		# execute console command "mogsound %player% block.note.pling 1.2 1.122"#g+ a-
		# execute console command "mogsound %player% block.note.pling 1.2 1.189"#a
		# execute console command "mogsound %player% block.note.pling 1.2 1.260"#a+ b-
		# execute console command "mogsound %player% block.note.pling 1.2 1.335"#b
		# execute console command "mogsound %player% block.note.pling 1.2 1.414"#c
		# execute console command "mogsound %player% block.note.pling 1.2 1.498"#c+ d-
		# execute console command "mogsound %player% block.note.pling 1.2 1.587"#d
		# execute console command "mogsound %player% block.note.pling 1.2 1.682"#d+ e-
		# execute console command "mogsound %player% block.note.pling 1.2 1.782"#e
		# execute console command "mogsound %player% block.note.pling 1.2 1.888"#f
		# execute console command "mogsound %player% block.note.pling 1.2 2"#f+ g-
# on right click:
	# player is op:
		# execute console command "mogsound %player% block.note.pling 1.2 0.891"#e
		# wait 6 tick
		# execute console command "mogsound %player% block.note.pling 1.2 0.707"#c
		# wait 6 tick
		# execute console command "mogsound %player% block.note.pling 1.2 0.530"#g
		# wait 6 tick
		# execute console command "mogsound %player% block.note.pling 1.2 0.707"#c
		# wait 6 tick
		# execute console command "mogsound %player% block.note.pling 1.2 0.794"#d
		# wait 6 tick
		# execute console command "mogsound %player% block.note.pling 1.2 1.059"#g
		# wait 6 tick
		# wait 6 tick
		# execute console command "mogsound %player% block.note.pling 1.2 0.530"#g
		# wait 6 tick
		# execute console command "mogsound %player% block.note.pling 1.2 0.794"#d
		# wait 6 tick
		# execute console command "mogsound %player% block.note.pling 1.2 0.891"#e
		# wait 6 tick
		# execute console command "mogsound %player% block.note.pling 1.2 0.794"#d
		# wait 6 tick
		# execute console command "mogsound %player% block.note.pling 1.2 0.530"#g
		# wait 6 tick
		# execute console command "mogsound %player% block.note.pling 1.2 0.707"#c


# command /goo:
	# trigger:
		# set the lore of held item to "&fUse the command||&a/warpset (number) (name)&f to ||&fset the warp point.|| ||&fSet this block at||&fCITY and right click||&fto open teleport menu."


# command test:
	# trigger:
		# create client side holo object "test" with id "tut1" at location of player to player

# command /testt:
	# trigger:
		# execute console command "mogsound dotoo entity.experience_orb.pickup 2 0.8"
		# wait 2 tick
		# execute console command "mogsound dotoo entity.experience_orb.pickup 2 0.9"
		# wait 2 tick
		# execute console command "mogsound dotoo entity.experience_orb.pickup 2 1"
		# wait 2 tick
		# execute console command "mogsound dotoo entity.player.levelup 2 2"

		
		
# on block place of 397:3:
	# message "place" to player

# on right click:
	# name of clicked block contains "Hamuzon":
		# message "test" to player
# command /test:
	# trigger:
		# player is op
		# loop 20 times:
			# spawn zombies at block at {locvalen1}
			# set name of last spawned entity to "<green>リアじゅう"
			# set max health of last spawned entity to 100
			# heal the last spawned entity
			# apply speed 2 to last spawned entity
			# spawn zombies at block at {locvalen2}
			# set name of last spawned entity to "<green>リアじゅう"
			# set max health of last spawned entity to 100
			# apply speed 2 to last spawned entity
			# heal the last spawned entity
			# spawn zombies at block at {locvalen3}
			# set name of last spawned entity to "<green>リアじゅう"
			# set max health of last spawned entity to 100
			# heal the last spawned entity
			# apply speed 2 to last spawned entity

# command /test2:
	# trigger:
		# player is op
		# set {locvalen3} to location of player

# command /equiphead:
	# trigger:
		# if player is op:
			# if {equipmobhead%player%} is not set:
				# set {equipmobhead%player%} to 0
				# send "みぎくりで頭をかぶせられる = %{equipmobhead%player%}%" to player
			# else if {equipmobhead%player%} is 0:
				# set {equipmobhead%player%} to 1
				# send "みぎくりで頭をかぶせられる = %{equipmobhead%player%}%" to player
			# else:
				# set {equipmobhead%player%} to 0
				# send "みぎくりで頭をかぶせられる = %{equipmobhead%player%}%" to player

# on right click:
command /equiptarget:
	trigger:
	# if {equipmobhead%player%} = 1:
		# player is holding mob head item
	# cancel event
		set helmet of targeted entity to held item of player
# command /equiphead1 <player>:
	# trigger:
		# if player is op:
			# set helmet of arg-1 to held item of player

# on crackshot shoot:
	# if lore of held item is set:
		# name of held item contains "alpha blaster":
			# set name of held item to "&cこの銃使えなくなったから運営に交換してもらってね！"
			# if lore of held item contains "Warrior":
				# set {_hotenmodname} to "&fWarrior"
				# set {_color} to "&f"
			# else if lore of held item contains "Hunter":
				# set {_hotenmodname} to "&fHunter"
				# set {_color} to "&f"
			# else if lore of held item contains "Ranger":
				# set {_hotenmodname} to "&fRanger"
				# set {_color} to "&f"
			# else if lore of held item contains "Marksman":
				# set {_hotenmodname} to "&fMarksman"
				# set {_color} to "&f"
			# else if lore of held item contains "Stalker":
				# set {_hotenmodname} to "&fStalker"
				# set {_color} to "&f"
			# else if lore of held item contains "Raider":
				# set {_hotenmodname} to "&fRaider"
				# set {_color} to "&f"
			# else if lore of held item contains "Knight":
				# set {_hotenmodname} to "&cKnight"
				# set {_color} to "&c"
			# else if lore of held item contains "Gladiator":
				# set {_hotenmodname} to "&cGladiator"
				# set {_color} to "&c"
			# else if lore of held item contains "Sentinel":
				# set {_hotenmodname} to "&cSentinel"
				# set {_color} to "&c"
			# else if lore of held item contains "Deadeye":
				# set {_hotenmodname} to "&cDeadeye"
				# set {_color} to "&c"
			# else if lore of held item contains "Champion":
				# set {_hotenmodname} to "&cChampion"
				# set {_color} to "&c"
			# else if lore of held item contains "Warlord":
				# set {_hotenmodname} to "&6Warlord"
				# set {_color} to "&6"
			# else if lore of held item contains "Monarch":
				# set {_hotenmodname} to "&6Monarch"
				# set {_color} to "&6"
			# else if lore of held item contains "Emperor":
				# set {_hotenmodname} to "&6Emperor"
				# set {_color} to "&6"
			
			# if lore of held item contains "III":
				# set {_lv} to "III"
				# set {_color2} to "&5"
			# else if lore of held item contains "II":
				# set {_lv} to "II"
				# set {_color2} to "&3"
			# else if lore of held item contains "I":
				# set {_lv} to "I"
				# set {_color2} to "&7"
				
			# if lore of held item contains "life":
				# set {_hotenenchname} to "Life Steal"
			# else if lore of held item contains "mana":
				# set {_hotenenchname} to "Mana Spring"
			# else if lore of held item contains "last":
				# set {_hotenenchname} to "Last Stand"
			# else if lore of held item contains "bli":
				# set {_hotenenchname} to "Bliss"
			# else if lore of held item contains "sun":
				# set {_hotenenchname} to "Sunfire"
			# else if lore of held item contains "sha":
				# set {_hotenenchname} to "Shadowmeld"
			# else if lore of held item contains "bri":
				# set {_hotenenchname} to "Brilliance"
			# else if lore of held item contains "pro":
				# set {_hotenenchname} to "Protector"
			# else if lore of held item contains "ber":
				# set {_hotenenchname} to "Berserk"
			# else if lore of held item contains "dar":
				# set {_hotenenchname} to "Dark Ritual"
			
			# remove held item from player
			
			# if {_hotenenchname} is not set:
				# if {_hotenmodname} is not set:
					# give crackshot weapon "alphaphaser" to player
				# else:
					# set {_hotenenchfinal} to "%{_color2}%Ench: %{_hotenenchname}% %{_lv}%"
					# set {_hotenmodnamefinal} to "%{_color}%Mod: %{_hotenmodname}% Mod"
					# give crackshot weapon "alphaphaser" with lore "%{_hotenmodnamefinal}%" to player
			
			# else if {_hotenmodname} is not set:
				# set {_hotenenchfinal} to "%{_color2}%Ench: %{_hotenenchname}% %{_lv}%"
				# set {_hotenmodnamefinal} to "%{_color}%Mod: %{_hotenmodname}% Mod"
				# give crackshot weapon "alphaphaser" with lore " ||%{_hotenenchfinal}%" to player
			# else:
				# set {_hotenenchfinal} to "%{_color2}%Ench: %{_hotenenchname}% %{_lv}%"
				# set {_hotenmodnamefinal} to "%{_color}%Mod: %{_hotenmodname}% Mod"
				# give crackshot weapon "alphaphaser" with lore "%{_hotenmodnamefinal}%||%{_hotenenchfinal}%" to player
				
		# name of held item contains "beta blaster":
			# set name of held item to "&cこの銃使えなくなったから運営に交換してもらってね！"
			# if lore of held item contains "Warrior":
				# set {_hotenmodname} to "&fWarrior"
				# set {_color} to "&f"
			# else if lore of held item contains "Hunter":
				# set {_hotenmodname} to "&fHunter"
				# set {_color} to "&f"
			# else if lore of held item contains "Ranger":
				# set {_hotenmodname} to "&fRanger"
				# set {_color} to "&f"
			# else if lore of held item contains "Marksman":
				# set {_hotenmodname} to "&fMarksman"
				# set {_color} to "&f"
			# else if lore of held item contains "Stalker":
				# set {_hotenmodname} to "&fStalker"
				# set {_color} to "&f"
			# else if lore of held item contains "Raider":
				# set {_hotenmodname} to "&fRaider"
				# set {_color} to "&f"
			# else if lore of held item contains "Knight":
				# set {_hotenmodname} to "&cKnight"
				# set {_color} to "&c"
			# else if lore of held item contains "Gladiator":
				# set {_hotenmodname} to "&cGladiator"
				# set {_color} to "&c"
			# else if lore of held item contains "Sentinel":
				# set {_hotenmodname} to "&cSentinel"
				# set {_color} to "&c"
			# else if lore of held item contains "Deadeye":
				# set {_hotenmodname} to "&cDeadeye"
				# set {_color} to "&c"
			# else if lore of held item contains "Champion":
				# set {_hotenmodname} to "&cChampion"
				# set {_color} to "&c"
			# else if lore of held item contains "Warlord":
				# set {_hotenmodname} to "&6Warlord"
				# set {_color} to "&6"
			# else if lore of held item contains "Monarch":
				# set {_hotenmodname} to "&6Monarch"
				# set {_color} to "&6"
			# else if lore of held item contains "Emperor":
				# set {_hotenmodname} to "&6Emperor"
				# set {_color} to "&6"
			
			# if lore of held item contains "III":
				# set {_lv} to "III"
				# set {_color2} to "&5"
			# else if lore of held item contains "II":
				# set {_lv} to "II"
				# set {_color2} to "&3"
			# else if lore of held item contains "I":
				# set {_lv} to "I"
				# set {_color2} to "&7"
				
			# if lore of held item contains "life":
				# set {_hotenenchname} to "Life Steal"
			# else if lore of held item contains "mana":
				# set {_hotenenchname} to "Mana Spring"
			# else if lore of held item contains "last":
				# set {_hotenenchname} to "Last Stand"
			# else if lore of held item contains "bli":
				# set {_hotenenchname} to "Bliss"
			# else if lore of held item contains "sun":
				# set {_hotenenchname} to "Sunfire"
			# else if lore of held item contains "sha":
				# set {_hotenenchname} to "Shadowmeld"
			# else if lore of held item contains "bri":
				# set {_hotenenchname} to "Brilliance"
			# else if lore of held item contains "pro":
				# set {_hotenenchname} to "Protector"
			# else if lore of held item contains "ber":
				# set {_hotenenchname} to "Berserk"
			# else if lore of held item contains "dar":
				# set {_hotenenchname} to "Dark Ritual"
			
			# remove held item from player
			
			# if {_hotenenchname} is not set:
				# if {_hotenmodname} is not set:
					# give crackshot weapon "betaphaser" to player
				# else:
					# set {_hotenenchfinal} to "%{_color2}%Ench: %{_hotenenchname}% %{_lv}%"
					# set {_hotenmodnamefinal} to "%{_color}%Mod: %{_hotenmodname}% Mod"
					# give crackshot weapon "betaphaser" with lore "%{_hotenmodnamefinal}%" to player
			
			# else if {_hotenmodname} is not set:
				# set {_hotenenchfinal} to "%{_color2}%Ench: %{_hotenenchname}% %{_lv}%"
				# set {_hotenmodnamefinal} to "%{_color}%Mod: %{_hotenmodname}% Mod"
				# give crackshot weapon "betaphaser" with lore " ||%{_hotenenchfinal}%" to player
			# else:
				# set {_hotenenchfinal} to "%{_color2}%Ench: %{_hotenenchname}% %{_lv}%"
				# set {_hotenmodnamefinal} to "%{_color}%Mod: %{_hotenmodname}% Mod"
				# give crackshot weapon "betaphaser" with lore "%{_hotenmodnamefinal}%||%{_hotenenchfinal}%" to player
		
# every 5 minutes:
	# loop all players:
		# if loop-player is in world "city":
			# if location of loop-player is equal to {test%loop-player%}:
				# execute loop-player command "spawn"
				# message "&7Sending you back to lobby because you were afk." to loop-player
			# else:
				# set {test%loop-player%} to location of loop-player





#on right click:
#	spawn a wave effect at location of player with id "%player%" with particle flame
#	spawn a animated ball effect at player with id "%player%"
#	spawn a tornado effect at location of player with id "%player%" with tornado particle flame and cloud particle cloud and radius 3 and max height 4
#	spawn a text effect with text "Hamu" as lava at location of player with id "%player%" and 1 large
#	wait 10 seconds
#	delete effect "%player%"


			# &f&7&m&l----------------------------------\n
			# &6&lTHE &eWAR &cII \n
			# &f&7&m&l----------------------------------
			
			# &f&7&m&l----------------------------------\n
			
			# &fYou are in &cMoosh Team &f!!\n
			# &fYou are in &aCreeper Team &f!!\n
			
			# &f&7&m&l----------------------------------
			
			
# command /hi:
	# trigger:
		# send player title " " with subtitle "&7hamu---!" for 3 seconds
		# wait 1 second
		# send player title " " with subtitle "&7bacon!" for 3 seconds
		

#on right click:
#	show 50 spell particles at location of player with color 100, 100, 100 offset by 3, 1, 3 with speed 2